# Generated by Django 4.1.3 on 2022-12-04 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_simpleaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleAccount',
        ),
    ]
