# Generated by Django 4.1.3 on 2022-11-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('TestId', models.AutoField(primary_key=True, serialize=False)),
                ('TestName', models.CharField(max_length=400)),
            ],
        ),
    ]
