# Generated by Django 4.1.3 on 2022-12-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0002_inventory_lowinventory_menu_orderdetails_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
