# Generated by Django 4.1.3 on 2022-12-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0004_simpleaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleaccount',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
