# Generated by Django 4.1.3 on 2022-12-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0006_alter_simpleaccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleaccount',
            name='is_auth',
            field=models.BooleanField(default=False),
        ),
    ]
