# Generated by Django 4.1.3 on 2022-12-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManagerApp', '0007_simpleaccount_is_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simpleaccount',
            old_name='is_staff',
            new_name='is_manager',
        ),
        migrations.AddField(
            model_name='simpleaccount',
            name='is_server',
            field=models.BooleanField(default=False),
        ),
    ]
